services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

  app:
    build:
      dockerfile: ./docker/Dockerfile
    container_name: app
   # restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www
